### ISSUE TITLE
Issue with the SMWG/Observatory tree in hpde.io

### ISSUE THREAD

**Issue by BaptisteCecconi** [hpde/SMWG#7]
Following #6, I checked the https://hpde.io portal.

I find that the [SMWG/Observatory](https://hpde.io/SMWG/Observatory/) tree has an issue: 

Selecting `SRN`, directly get to the [spase://SMWG/Observatory/SRN](https://hpde.io/SMWG/Observatory/SRN.html) record. However, I don't see how to browse down to [spase://SMWG/Observatory/SRN/NDA](https://hpde.io/SMWG/Observatory/SRN/NDA.html). 

It might not be a bug, since the page is there, but there is no obvious way to click our way to that page.

**Comment by rchimiak** [comment]
Under https://hpde.io/SMWG/Observatory/index.html there are two entries for SRN, one for the descriptor itself https://hpde.io/SMWG/Observatory/SRN.html and one for the tree that contains the NDA entry along with other shttps://hpde.io/SMWG/Observatory/SRN/NDA.html  
The problem is that there is no visual difference between the SRN folder and the SRN page.

**Comment by BaptisteCecconi** [comment]
Ah ! yes, thanks @rchimiak 
I missed the first instance. Yes, as you say, there should be a visual difference between the folders and pages.
